# Generated by Django 3.0.3 on 2020-02-27 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20200227_1648'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='Units',
        ),
    ]
