# Generated by Django 3.0.3 on 2020-02-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20200227_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='RW',
            fields=[
                ('Name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Strength', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Damage', models.CharField(max_length=10)),
                ('Range', models.DecimalField(decimal_places=2, max_digits=5)),
                ('AP', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Type', models.CharField(max_length=15)),
                ('Attacks', models.CharField(max_length=10)),
                ('Points', models.IntegerField()),
                ('Mode', models.BooleanField()),
                ('Special', models.BooleanField()),
            ],
        ),
    ]
